sudo: required

language: java
jdk:
- oraclejdk8

after_success:
- bash <(curl -s https://codecov.io/bash)

services:
- docker

deploy:
  provider: script
  script: bash docker_push.sh
  skip_cleanup: true
  on:
    branch: master



