sudo: required

language: java
jdk:
- oraclejdk8

after_success:
- bash <(curl -s https://codecov.io/bash)

services:
- docker


#deploy:
#- provider: elasticbeanstalk
#  access_key_id: $AWS_ACCESS_KEY_ID
#  secret_access_key: $AWS_SECRET_ACCESS_KEY
#  region: us-west-2
#  app: basic-cloud-workshop-app
#  env: BasicCloudWorkshopApp-dev
#  bucket_name: basic-cloud-workshop-app
#  zip_file: './build/libs/basic-cloud-workshop-app-0.0.1-SNAPSHOT.jar'
#  skip_cleanup: true
#  on:
#    branch: master
#
#- provider: script
#  script: bash docker_push.sh
#  skip_cleanup: true
#  on:
#    branch: master